version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true

services:
  
  jupyterlab:
    image: jupyterlab
    container_name: ${PROJECT_NAME}-jupyterlab
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - .env
    ports:
      - ${JUPYTERLAB_PORT}:8888

  spark-master:
    image: spark-master
    container_name: ${PROJECT_NAME}-spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      SPARK_LOCAL_IP: ${SPARK_LOCAL_IP}
    env_file:
      - .env
    ports:
      - ${SPARK_MASTER_PORT_1}:8080
      - ${SPARK_MASTER_PORT_2}:7077
    
  spark-worker-1:
    image: spark-worker
    container_name: ${PROJECT_NAME}-spark-worker-1
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    env_file:
      - .env
    ports:
      - ${SPARK_WORKER_1_PORT}:8081
    
  
  spark-worker-2:
    image: spark-worker
    container_name: ${PROJECT_NAME}-spark-worker-2
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    env_file:
      - .env
    ports:
      - ${SPARK_WORKER_2_PORT}:8081
    
