version: '3'
networks:
  default:
    name: ashraf-magic-network
    external: true

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ashraf
      - POSTGRES_DB=de_zoomcamp_data
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ashraf@admin.com
      - PGADMIN_DEFAULT_PASSWORD=ashraf
    ports:
      - "80:80"
